name: starge-infra

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - ./env/infra.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U starge"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    env_file:
      - ./env/infra.env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    restart: unless-stopped
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
    env_file:
      - ./env/infra.env
    networks:
      - backend_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    restart: unless-stopped
    volumes:
      - kafka_data:/var/lib/kafka/data
    env_file:
      - ./env/infra.env
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      - zookeeper
    networks:
      - backend_network

networks:
  backend_network:
    name: backend_network
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  zookeeper_data:
  kafka_data: