name: starge-frontend

services:
  frontend:
    image: ghcr.io/tarasdemchenkooo/starge-frontend:${TAG}
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.rule=Host(`starge.xyz`)
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.certresolver=cloudflare
    networks:
      - traefik_network
    
networks:
  traefik_network:
    name: traefik_network
    external: true