apiVersion: 1

groups:
  - orgId: 1
    name: Node Alerts
    folder: Node
    interval: 1m
    rules:
      - uid: cpu_usage
        title: CPU Usage
        condition: B
        for: 5m
        data:
          - refId: A
            datasourceUid: prometheus
            relativeTimeRange:
              from: 300
              to: 0
            model:
              editorMode: code
              expr: 100 * (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m])))
              intervalMs: 15000
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [90]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [B]
                  reducer:
                    params: []
                    type: last
                  type: query
              expression: A
              intervalMs: 15000
              maxDataPoints: 43200
              type: threshold
              refId: B
        noDataState: NoData
        execErrState: Error
        labels:
          category: system
          severity: high
        annotations:
          summary: CPU usage is too high
          description: CPU usage has exceeded 90% for the last 5 minutes\.