apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram
    receivers:
      - uid: telegram
        type: telegram
        disableResolveMessage: false
        settings:
          bottoken: ${TELEGRAM_BOT_TOKEN}
          chatid: ${TELEGRAM_CHAT_ID}
          parse_mode: MarkdownV2
          message: |
            *Category: {{ .Labels.category }}*
            *{{ .Annotations.summary }}*
            
            _{{ .Annotations.description }}_"