name: starge-services

services:
  api-gateway:
    image: ghcr.io/tarasdemchenkooo/starge-backend_api-gateway:${TAG}
    env_file:
      - ./env/api-gateway.env
    labels:
      - service=api-gateway
      - promtail.scrape=true
      - traefik.enable=true
      - traefik.docker.network=traefik_network
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.rule=Host(`api.starge.xyz`)
      - traefik.http.services.api.loadbalancer.server.port=79
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=resolver
    networks:
      - traefik_network
      - backend_network

  payment-service:
    image: ghcr.io/tarasdemchenkooo/starge-backend_payment-service:${TAG}
    env_file:
      - ./env/payment-service.env
    labels:
      - service=payment-service
      - promtail.scrape=true
      - traefik.enable=true
      - traefik.docker.network=traefik_network
      - traefik.http.routers.bot.entrypoints=websecure
      - >
        traefik.http.routers.bot.rule=Host(`api.starge.xyz`) &&
        Path(`${BOT_SECRET_PATH}`) &&
        Header(`X-Telegram-Bot-Api-Secret-Token`, `${BOT_API_SECRET}`)
      - traefik.http.services.bot.loadbalancer.server.port=78
      - traefik.http.routers.bot.tls=true
      - traefik.http.routers.bot.tls.certresolver=resolver
    networks:
      - traefik_network
      - backend_network

  ton-aggregator:
    image: ghcr.io/tarasdemchenkooo/starge-backend_transaction-aggregator:${TAG}
    env_file:
      - ./env/ton-aggregator.env
    labels:
      - service=transaction-aggregator
      - promtail.scrape=true
    networks:
      - backend_network

  usdt-aggregator:
    image: ghcr.io/tarasdemchenkooo/starge-backend_transaction-aggregator:${TAG}
    env_file:
      - ./env/usdt-aggregator.env
    labels:
      - service=transaction-aggregator
      - promtail.scrape=true
    networks:
      - backend_network

  ton-processor:
    image: ghcr.io/tarasdemchenkooo/starge-backend_processing-service:${TAG}
    env_file:
      - ./env/ton-processor.env
    labels:
      - service=processing-service
      - promtail.scrape=true
    networks:
      - backend_network

  usdt-processor:
    image: ghcr.io/tarasdemchenkooo/starge-backend_processing-service:${TAG}
    env_file:
      - ./env/usdt-processor.env
    labels:
      - service=processing-service
      - promtail.scrape=true
    networks:
      - backend_network

  notification-service:
    image: ghcr.io/tarasdemchenkooo/starge-backend_notification-service:${TAG}
    env_file:
      - ./env/notification-service.env
    labels:
      - service=notification-service
      - promtail.scrape=true
    networks:
      - backend_network

networks:
  traefik_network:
    name: traefik_network
    external: true
  backend_network:
    name: backend_network
    external: true