auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /etc/loki
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1

storage_config:
  filesystem:
    directory: /etc/loki/chunks
  tsdb_shipper:
    active_index_directory: /etc/loki/tsdb-index
    cache_location: /etc/loki/tsdb-cache
    cache_ttl: 24h

schema_config:
  configs:
  - from: 2025-01-01
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

limits_config:
  allow_structured_metadata: true
  volume_enabled: true
  retention_period: 168h