server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /var/log/positions.yaml
  sync_period: 5s

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    pipeline_stages:
      - drop:
          expression: ^(?!.*include_service_log).*$
          drop_counter_reason: internal_log
      - json:
          expressions:
            timestamp: time
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - structured_metadata:
          container_id:
    relabel_configs:
      - source_labels: [__meta_docker_container_label_service]
        target_label: service
      - source_labels: [__meta_docker_container_id]
        target_label: container_id