server:
  http_listen_port: 9080

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /var/log/positions.yaml
  sync_period: 5s

scrape_configs:
  - job_name: docker

    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        filters:
          - name: label
            values: [promtail.scrape=true]
        refresh_interval: 5s

    pipeline_stages:
      - json:
          expressions:
            external_log:
            level:
            timestamp:
          drop_malformed: true
      - template:
          source: external_log
          template: '{{ if eq .Value "true" }}true{{ else }}false{{ end }}'
      - drop:
          source: external_log
          value: 'false'
          drop_counter_reason: internal_log
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - structured_metadata:
          container_id:
          
    relabel_configs:
      - source_labels: [__meta_docker_container_label_service]
        target_label: service
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      - action: labeldrop
        regex: service_name